spring.application.name=hotel-manager-api
# 1. Database Connection
spring.datasource.url=jdbc:postgresql://dpg-d6p6dhpj16oc738tb6k0-a.singapore-postgres.render.com/hotelbookingdb_bgo8
spring.datasource.username=hotelbookingdb_bgo8_user
spring.datasource.password=9D2bnfM6A94pCkhKQmPFsCi3RDFImori
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. JPA / Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true