spring:
  application:
    name: hotel-manager-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: 86400000
